slug: create-parquet-file-in-datalake-storage-gen2-(adls-gen2)-using-open-dataset-with-synapse-spark
title: Create Parquet file in Data Lake Storage Gen2 (ADLS Gen2) using Open Dataset with Synapse Spark
difficulty: Beginner
validation_type: Basic
